default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: ynyw_development


test:
  <<: *default
  database: ynyw_test

production:
  <<: *default
  database: ynyw_production
  username: ynyw
  password: <%= ENV['YNYW _DATABASE_PASSWORD'] %>
